import { ContinentMapping, Iso2AlphaCountry } from "@/types";

export const isoAlpha2Countries: Iso2AlphaCountry = {
  AD: { name: "Andorra", continent: "Europe" },
  AE: { name: "United Arab Emirates", continent: "Asia" },
  AF: { name: "Afghanistan", continent: "Asia" },
  AG: { name: "Antigua and Barbuda", continent: "North America" },
  AI: { name: "Anguilla", continent: "North America" },
  AL: { name: "Albania", continent: "Europe" },
  AM: { name: "Armenia", continent: "Asia" },
  AO: { name: "Angola", continent: "Africa" },
  AQ: { name: "Antarctica", continent: "Antarctica" },
  AR: { name: "Argentina", continent: "South America" },
  AS: { name: "American Samoa", continent: "Oceania" },
  AT: { name: "Austria", continent: "Europe" },
  AU: { name: "Australia", continent: "Oceania" },
  AW: { name: "Aruba", continent: "North America" },
  AX: { name: "Åland Islands", continent: "Europe" },
  AZ: { name: "Azerbaijan", continent: "Asia" },
  BA: { name: "Bosnia and Herzegovina", continent: "Europe" },
  BB: { name: "Barbados", continent: "North America" },
  BD: { name: "Bangladesh", continent: "Asia" },
  BE: { name: "Belgium", continent: "Europe" },
  BF: { name: "Burkina Faso", continent: "Africa" },
  BG: { name: "Bulgaria", continent: "Europe" },
  BH: { name: "Bahrain", continent: "Asia" },
  BI: { name: "Burundi", continent: "Africa" },
  BJ: { name: "Benin", continent: "Africa" },
  BL: { name: "Saint Barthélemy", continent: "North America" },
  BM: { name: "Bermuda", continent: "North America" },
  BN: { name: "Brunei Darussalam", continent: "Asia" },
  BO: { name: "Bolivia", continent: "South America" },
  BQ: { name: "Bonaire, Sint Eustatius and Saba", continent: "North America" },
  BR: { name: "Brazil", continent: "South America" },
  BS: { name: "Bahamas", continent: "North America" },
  BT: { name: "Bhutan", continent: "Asia" },
  BV: { name: "Bouvet Island", continent: "Antarctica" },
  BW: { name: "Botswana", continent: "Africa" },
  BY: { name: "Belarus", continent: "Europe" },
  BZ: { name: "Belize", continent: "North America" },
  CA: { name: "Canada", continent: "North America" },
  CC: { name: "Cocos (Keeling) Islands", continent: "Asia" },
  CD: { name: "Congo, the Democratic Republic of the", continent: "Africa" },
  CF: { name: "Central African Republic", continent: "Africa" },
  CG: { name: "Congo", continent: "Africa" },
  CH: { name: "Switzerland", continent: "Europe" },
  CI: { name: "Côte d'Ivoire", continent: "Africa" },
  CK: { name: "Cook Islands", continent: "Oceania" },
  CL: { name: "Chile", continent: "South America" },
  CM: { name: "Cameroon", continent: "Africa" },
  CN: { name: "China", continent: "Asia" },
  CO: { name: "Colombia", continent: "South America" },
  CR: { name: "Costa Rica", continent: "North America" },
  CU: { name: "Cuba", continent: "North America" },
  CV: { name: "Cape Verde", continent: "Africa" },
  CW: { name: "Curaçao", continent: "North America" },
  CX: { name: "Christmas Island", continent: "Asia" },
  CY: { name: "Cyprus", continent: "Asia" },
  CZ: { name: "Czech Republic", continent: "Europe" },
  DE: { name: "Germany", continent: "Europe" },
  DJ: { name: "Djibouti", continent: "Africa" },
  DK: { name: "Denmark", continent: "Europe" },
  DM: { name: "Dominica", continent: "North America" },
  DO: { name: "Dominican Republic", continent: "North America" },
  DZ: { name: "Algeria", continent: "Africa" },
  EC: { name: "Ecuador", continent: "South America" },
  EE: { name: "Estonia", continent: "Europe" },
  EG: { name: "Egypt", continent: "Africa" },
  EH: { name: "Western Sahara", continent: "Africa" },
  ER: { name: "Eritrea", continent: "Africa" },
  ES: { name: "Spain", continent: "Europe" },
  ET: { name: "Ethiopia", continent: "Africa" },
  FI: { name: "Finland", continent: "Europe" },
  FJ: { name: "Fiji", continent: "Oceania" },
  FK: { name: "Falkland Islands (Malvinas)", continent: "South America" },
  FM: { name: "Micronesia, Federated States of", continent: "Oceania" },
  FO: { name: "Faroe Islands", continent: "Europe" },
  FR: { name: "France", continent: "Europe" },
  GA: { name: "Gabon", continent: "Africa" },
  GB: { name: "United Kingdom", continent: "Europe" },
  GD: { name: "Grenada", continent: "North America" },
  GE: { name: "Georgia", continent: "Asia" },
  GF: { name: "French Guiana", continent: "South America" },
  GG: { name: "Guernsey", continent: "Europe" },
  GH: { name: "Ghana", continent: "Africa" },
  GI: { name: "Gibraltar", continent: "Europe" },
  GL: { name: "Greenland", continent: "North America" },
  GM: { name: "Gambia", continent: "Africa" },
  GN: { name: "Guinea", continent: "Africa" },
  GP: { name: "Guadeloupe", continent: "North America" },
  GQ: { name: "Equatorial Guinea", continent: "Africa" },
  GR: { name: "Greece", continent: "Europe" },
  GS: {
    name: "South Georgia and the South Sandwich Islands",
    continent: "Antarctica",
  },
  GT: { name: "Guatemala", continent: "North America" },
  GU: { name: "Guam", continent: "Oceania" },
  GW: { name: "Guinea-Bissau", continent: "Africa" },
  GY: { name: "Guyana", continent: "South America" },
  HK: { name: "Hong Kong", continent: "Asia" },
  HM: { name: "Heard Island and McDonald Islands", continent: "Antarctica" },
  HN: { name: "Honduras", continent: "North America" },
  HR: { name: "Croatia", continent: "Europe" },
  HT: { name: "Haiti", continent: "North America" },
  HU: { name: "Hungary", continent: "Europe" },
  ID: { name: "Indonesia", continent: "Asia" },
  IE: { name: "Ireland", continent: "Europe" },
  IL: { name: "Israel", continent: "Asia" },
  IM: { name: "Isle of Man", continent: "Europe" },
  IN: { name: "India", continent: "Asia" },
  IO: { name: "British Indian Ocean Territory", continent: "Africa" },
  IQ: { name: "Iraq", continent: "Asia" },
  IR: { name: "Iran, Islamic Republic of", continent: "Asia" },
  IS: { name: "Iceland", continent: "Europe" },
  IT: { name: "Italy", continent: "Europe" },
  JE: { name: "Jersey", continent: "Europe" },
  JM: { name: "Jamaica", continent: "North America" },
  JO: { name: "Jordan", continent: "Asia" },
  JP: { name: "Japan", continent: "Asia" },
  KE: { name: "Kenya", continent: "Africa" },
  KG: { name: "Kyrgyzstan", continent: "Asia" },
  KH: { name: "Cambodia", continent: "Asia" },
  KI: { name: "Kiribati", continent: "Oceania" },
  KM: { name: "Comoros", continent: "Africa" },
  KN: { name: "Saint Kitts and Nevis", continent: "North America" },
  KP: { name: "Korea, Democratic People's Republic of", continent: "Asia" },
  KR: { name: "Korea, Republic of", continent: "Asia" },
  KW: { name: "Kuwait", continent: "Asia" },
  KY: { name: "Cayman Islands", continent: "North America" },
  KZ: { name: "Kazakhstan", continent: "Asia" },
  LA: { name: "Lao People's Democratic Republic", continent: "Asia" },
  LB: { name: "Lebanon", continent: "Asia" },
  LC: { name: "Saint Lucia", continent: "North America" },
  LI: { name: "Liechtenstein", continent: "Europe" },
  LK: { name: "Sri Lanka", continent: "Asia" },
  LR: { name: "Liberia", continent: "Africa" },
  LS: { name: "Lesotho", continent: "Africa" },
  LT: { name: "Lithuania", continent: "Europe" },
  LU: { name: "Luxembourg", continent: "Europe" },
  LV: { name: "Latvia", continent: "Europe" },
  LY: { name: "Libya", continent: "Africa" },
  MA: { name: "Morocco", continent: "Africa" },
  MC: { name: "Monaco", continent: "Europe" },
  MD: { name: "Moldova, Republic of", continent: "Europe" },
  ME: { name: "Montenegro", continent: "Europe" },
  MF: { name: "Saint Martin (French part)", continent: "North America" },
  MG: { name: "Madagascar", continent: "Africa" },
  MH: { name: "Marshall Islands", continent: "Oceania" },
  MK: {
    name: "Macedonia, the former Yugoslav Republic of",
    continent: "Europe",
  },
  ML: { name: "Mali", continent: "Africa" },
  MM: { name: "Myanmar", continent: "Asia" },
  MN: { name: "Mongolia", continent: "Asia" },
  MO: { name: "Macao", continent: "Asia" },
  MP: { name: "Northern Mariana Islands", continent: "Oceania" },
  MQ: { name: "Martinique", continent: "North America" },
  MR: { name: "Mauritania", continent: "Africa" },
  MS: { name: "Montserrat", continent: "North America" },
  MT: { name: "Malta", continent: "Europe" },
  MU: { name: "Mauritius", continent: "Africa" },
  MV: { name: "Maldives", continent: "Asia" },
  MW: { name: "Malawi", continent: "Africa" },
  MX: { name: "Mexico", continent: "North America" },
  MY: { name: "Malaysia", continent: "Asia" },
  MZ: { name: "Mozambique", continent: "Africa" },
  NA: { name: "Namibia", continent: "Africa" },
  NC: { name: "New Caledonia", continent: "Oceania" },
  NE: { name: "Niger", continent: "Africa" },
  NF: { name: "Norfolk Island", continent: "Oceania" },
  NG: { name: "Nigeria", continent: "Africa" },
  NI: { name: "Nicaragua", continent: "North America" },
  NL: { name: "Netherlands", continent: "Europe" },
  NO: { name: "Norway", continent: "Europe" },
  NP: { name: "Nepal", continent: "Asia" },
  NR: { name: "Nauru", continent: "Oceania" },
  NU: { name: "Niue", continent: "Oceania" },
  NZ: { name: "New Zealand", continent: "Oceania" },
  OM: { name: "Oman", continent: "Asia" },
  PA: { name: "Panama", continent: "North America" },
  PE: { name: "Peru", continent: "South America" },
  PF: { name: "French Polynesia", continent: "Oceania" },
  PG: { name: "Papua New Guinea", continent: "Oceania" },
  PH: { name: "Philippines", continent: "Asia" },
  PK: { name: "Pakistan", continent: "Asia" },
  PL: { name: "Poland", continent: "Europe" },
  PM: { name: "Saint Pierre and Miquelon", continent: "North America" },
  PN: { name: "Pitcairn", continent: "Oceania" },
  PR: { name: "Puerto Rico", continent: "North America" },
  PS: { name: "Palestine, State of", continent: "Asia" },
  PT: { name: "Portugal", continent: "Europe" },
  PW: { name: "Palau", continent: "Oceania" },
  PY: { name: "Paraguay", continent: "South America" },
  QA: { name: "Qatar", continent: "Asia" },
  RE: { name: "Réunion", continent: "Africa" },
  RO: { name: "Romania", continent: "Europe" },
  RS: { name: "Serbia", continent: "Europe" },
  RU: { name: "Russian Federation", continent: "Europe" },
  RW: { name: "Rwanda", continent: "Africa" },
  SA: { name: "Saudi Arabia", continent: "Asia" },
  SB: { name: "Solomon Islands", continent: "Oceania" },
  SC: { name: "Seychelles", continent: "Africa" },
  SD: { name: "Sudan", continent: "Africa" },
  SE: { name: "Sweden", continent: "Europe" },
  SG: { name: "Singapore", continent: "Asia" },
  SH: {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    continent: "Africa",
  },
  SI: { name: "Slovenia", continent: "Europe" },
  SJ: { name: "Svalbard and Jan Mayen", continent: "Europe" },
  SK: { name: "Slovakia", continent: "Europe" },
  SL: { name: "Sierra Leone", continent: "Africa" },
  SM: { name: "San Marino", continent: "Europe" },
  SN: { name: "Senegal", continent: "Africa" },
  SO: { name: "Somalia", continent: "Africa" },
  SR: { name: "Suriname", continent: "South America" },
  SS: { name: "South Sudan", continent: "Africa" },
  ST: { name: "Sao Tome and Principe", continent: "Africa" },
  SV: { name: "El Salvador", continent: "North America" },
  SX: { name: "Sint Maarten (Dutch part)", continent: "North America" },
  SY: { name: "Syrian Arab Republic", continent: "Asia" },
  SZ: { name: "Swaziland", continent: "Africa" },
  TC: { name: "Turks and Caicos Islands", continent: "North America" },
  TD: { name: "Chad", continent: "Africa" },
  TF: { name: "French Southern Territories", continent: "Antarctica" },
  TG: { name: "Togo", continent: "Africa" },
  TH: { name: "Thailand", continent: "Asia" },
  TJ: { name: "Tajikistan", continent: "Asia" },
  TK: { name: "Tokelau", continent: "Oceania" },
  TL: { name: "Timor-Leste", continent: "Asia" },
  TM: { name: "Turkmenistan", continent: "Asia" },
  TN: { name: "Tunisia", continent: "Africa" },
  TO: { name: "Tonga", continent: "Oceania" },
  TR: { name: "Turkey", continent: "Asia" },
  TT: { name: "Trinidad and Tobago", continent: "North America" },
  TV: { name: "Tuvalu", continent: "Oceania" },
  TW: { name: "Taiwan, Province of China", continent: "Asia" },
  TZ: { name: "Tanzania, United Republic of", continent: "Africa" },
  UA: { name: "Ukraine", continent: "Europe" },
  UG: { name: "Uganda", continent: "Africa" },
  UM: { name: "United States Minor Outlying Islands", continent: "Oceania" },
  US: { name: "United States", continent: "North America" },
  UY: { name: "Uruguay", continent: "South America" },
  UZ: { name: "Uzbekistan", continent: "Asia" },
  VA: { name: "Holy See (Vatican City State)", continent: "Europe" },
  VC: { name: "Saint Vincent and the Grenadines", continent: "North America" },
  VE: { name: "Venezuela, Bolivarian Republic of", continent: "South America" },
  VG: { name: "Virgin Islands, British", continent: "North America" },
  VI: { name: "Virgin Islands, U.S.", continent: "North America" },
  VN: { name: "Viet Nam", continent: "Asia" },
  VU: { name: "Vanuatu", continent: "Oceania" },
  WF: { name: "Wallis and Futuna", continent: "Oceania" },
  WS: { name: "Samoa", continent: "Oceania" },
  YE: { name: "Yemen", continent: "Asia" },
  YT: { name: "Mayotte", continent: "Africa" },
  ZA: { name: "South Africa", continent: "Africa" },
  ZM: { name: "Zambia", continent: "Africa" },
  ZW: { name: "Zimbabwe", continent: "Africa" },
};

export const formatContinent = (continent: string) => {
  const mapping: ContinentMapping = {
    Africa: { article: "an", name: "African" },
    America: { article: "an", name: "American" },
    Antarctica: { article: "an", name: "Antarctican" },
    Arctic: { article: "an", name: "Arctic" },
    Asia: { article: "an", name: "Asian" },
    Atlantic: { article: "an", name: "Atlantic" },
    Australia: { article: "an", name: "Australian" },
    Europe: { article: "a", name: "European" },
    Indian: { article: "an", name: "Indian" },
    "North America": { article: "a", name: "North American" },
    "South America": { article: "a", name: "South American" },
    Pacific: { article: "a", name: "Pacific" },
    Oceania: { article: "an", name: "Oceanic" },
  };

  return mapping[continent];
};

export const formatPrice = (price: number | null, currencyCode = "usd") => {
  const formatter = Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currencyCode,
  });

  if (!price) {
    return formatter.format(0);
  }

  return formatter.format(price / 100);
};
